version: '3.5'

services:
  db:
    image: postgres:12.0-alpine
    env_file:
      - .env
    volumes:
      - app-db:/var/lib/postgresql/data_template/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

  app:
    build: .
    env_file:
      - .env
    command: uvicorn app.main:app --host ${TRANSPORT_ADDRESS} --port ${TRANSPORT_PORT}
    environment:
      - POSTGRES_SERVER=db
      - DB_PORT=5432
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - VSCALE_URL=https://api.vscale.io/v1
      - VSCALE_TOKEN=${VSCALE_TOKEN}
    volumes:
      - .:/code
    ports:
      - "${TRANSPORT_PORT}:${TRANSPORT_PORT}"
    depends_on:
      - db

volumes:
  app-db:
    name: app-db